### ISSUE TITLE
init.vim被删

### ISSUE THREAD

**Issue by Adnios** [voldikss/coc-floaterm#2]
作者您好，我通过CocInstall coc-floaterm安装后，执行CocList floaterm后打开了fzf搜索的界面，然后我强制退出了nvim，重新进入后发现init.vim被删了

**Comment by voldikss** [comment]
无法复现
可以提交更详细的步骤或者Gif

**Comment by Adnios** [comment]
抱歉，我也感觉很奇怪，只发生了一次，我记得我当时执行CocList floaterm，打开了下面的界面，然后我按了o，之后就卡住了
![image](https://user-images.githubusercontent.com/41060790/80167204-5b72b980-8612-11ea-9e1a-83f250838143.png)

**Comment by Adnios** [comment]
应该是我之前的配置的问题，而且我的floaterm也没装成功，这个issue可以关闭了
